version: 2

sources:
  - name: RAW
    description: "RAW SOURCE TABLES FOR THE ECOMMERCE ANALYTICS PROJECT."
    database: "{{ target.database }}"
    schema: RAW


    tables:
      - name: RAW_CUSTOMERS
        description: "RAW CUSTOMERS DATA FROM SOURCE SYSTEM."
        columns:
          - name: CUSTOMER_ID
            description: "PRIMARY KEY FOR CUSTOMER."
            tests:
              - not_null

      - name: RAW_ORDERS
        description: "RAW ORDER HEADER DATA."
        columns:
          - name: ORDER_ID
            description: "PRIMARY KEY FOR ORDER."
            tests:
              - not_null

          - name: CUSTOMER_ID
            description: "FOREIGN KEY TO RAW_CUSTOMERS."
            tests:
              - not_null

          - name: ORDER_DATE
            description: "ORDER DATE."
            tests:
              - not_null

      - name: RAW_ORDER_ITEMS
        description: "RAW ORDER LINE ITEMS DATA."
        columns:
          - name: ORDER_ITEM_ID
            description: "PRIMARY KEY FOR ORDER LINE."
            tests:
              - not_null

          - name: ORDER_ID
            description: "PARENT ORDER ID."
            tests:
              - not_null

          - name: QUANTITY
            description: "QUANTITY OF PRODUCT ORDERED."
            tests:
              - not_null
    config:
      loaded_at_field: CREATED_AT
      freshness:
        warn_after: {count: 1, period: hour}
        error_after: {count: 4, period: hour}